load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "hello_world",
    srcs = [
        "HelloWorld.java",
        "utils/MyUtil.java"
    ],
    main_class = "com.example.project.HelloWorld",
)